
---
title: "Project Summary"
author: "Jenni Kane"
date: "February 25, 2021"
output:
  word_document: default
  pdf_document: default
---

Descripion of the study system and experimental design:

In spring of 2019, I established a field experiment at the WVU Agronomy and Animal Science farms to study the soil microbiome associated with the perennial grass Miscanthus x giganteus across varying fertilization regimes. The plots are established on land with a legacy of surface mining disturbance, either directly or indirectly. Each 5 x 5 meter plot contains approximately 25 Miscanthus plants. Plots are arranged in 16 blocks which each contain 4 plots recieving one of four fertilization treatments yearly. These treatments are: 1) Organic, consisting of composted dairy manure 2) Low Inorganic/Synthetic, consisting of 100 kg/hectare N addition as 15-15-15 N-P-K fertilizer 3) Low Inorganic/Synthetic, consisting of 300 kg/hectare N addition as 15-15-15 N-P-K fertilizer and 4) Control, consisting of no fertilization. In all the field experiment consists of 64 total plots arranged into 16 total blocks. 32 plots and 8 blocks are at each farm. Each treatment is replicated 16 total times, 8 times at each farm. 

List of questions: 

1) Does Miscanthus production on damaged land serve to regenerate soil properties (e.g., organic matter contant, structure, hydrology) and does this vary over different fertilization treatments?

2) Does microbial community structure predict crop yield and soil regeneration?

3) Does microbial community function mediate losses of nutrients (e.g., as CO2 respired or N leached) from these systems in a systematic way, varying with fertilization treatment?

List of response variables (predictor variable being the treatment regime described above):

For the 2019 field season, I have all of these. Some are still in process for the 2020 season (e.g., sequencing is being performed now)

  Total microbial biomass, 
  Total soil respiration,
  Bacterial and fungal DNA sequencing libraries (composition, diversity, abundance of organisms included),
  Nitrogen mineralization and immobilization, 
  Nitrogen and Carbon use efficiencies (calculated from respiration, biomass, and mineralization),
  Crop quality measures (Yield, height, number of shoots),
  Soil quality measures (Total C and N, total organic matter)


Another interesting thing is that there is a clear delineation in the data of one of my sites, which is clearly the lowest quality in terms of environmental conditions. It is also the most directly impacted by surface mining. 
